version: '3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest

  uwsgi:
    image: djangovuetify:latest
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app/
    command: uwsgi --ini /app/compose/uwsgi.ini

  nginx:
    image: nginx:1.13
    depends_on:
      - uwsgi
    volumes:
      - ./compose/nginx.conf:/etc/nginx/nginx.conf
      - ./:/app/
    ports:
      - "0.0.0.0:8000:8000"
